language: node_js
node_js:
  - "14"
services: mongodb  
cache:  
  directories:
  - "node_modules"
install:
  - rd /s /q node_modules
  - npm install
script:
  - npm test
deploy:
  - provider: script
    cleanup: true
    script: chmod +x ./deploy.sh && ./deploy.sh
    on:
      branch: master
